// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZwMUcKIv2uLBwcKwIrn1lR6fItKN_ic',
    appId: '1:443036827242:web:c2643b7a2f5a43dd9ed413',
    messagingSenderId: '443036827242',
    projectId: 'carsmanager-48ab8',
    authDomain: 'carsmanager-48ab8.firebaseapp.com',
    storageBucket: 'carsmanager-48ab8.appspot.com',
    measurementId: 'G-KH63X2ZN2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4QRYe4kOg-w72aQ_dPHK316T2F9a8mSg',
    appId: '1:443036827242:android:4c6d95295463f35e9ed413',
    messagingSenderId: '443036827242',
    projectId: 'carsmanager-48ab8',
    storageBucket: 'carsmanager-48ab8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIvnFhVxyp227vrTpbxkrfOfdizlSyIuA',
    appId: '1:443036827242:ios:02ee3cf08cdaa4759ed413',
    messagingSenderId: '443036827242',
    projectId: 'carsmanager-48ab8',
    storageBucket: 'carsmanager-48ab8.appspot.com',
    iosBundleId: 'com.example.carsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIvnFhVxyp227vrTpbxkrfOfdizlSyIuA',
    appId: '1:443036827242:ios:02ee3cf08cdaa4759ed413',
    messagingSenderId: '443036827242',
    projectId: 'carsmanager-48ab8',
    storageBucket: 'carsmanager-48ab8.appspot.com',
    iosBundleId: 'com.example.carsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZwMUcKIv2uLBwcKwIrn1lR6fItKN_ic',
    appId: '1:443036827242:web:c8dc327e3b8eda9e9ed413',
    messagingSenderId: '443036827242',
    projectId: 'carsmanager-48ab8',
    authDomain: 'carsmanager-48ab8.firebaseapp.com',
    storageBucket: 'carsmanager-48ab8.appspot.com',
    measurementId: 'G-8NF1WCNJNY',
  );
}
